# Disable sudo to speed up the build
sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip

install:
  - pip install -r requirements.txt
  - chmod +x travis_setup_env.sh && ./travis_setup_env.sh

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=audio

script:
  - python test_env/test_imports.py