# Disable sudo to speed up the build
sudo: false

language: python

# Because Beryl is going to run on Python 3.6 or later
python:
  - "3.6"
  - "3.7"
cache: pip

install:
  - pip install -r requirements.txt
  - chmod +x travis_setup_env.sh && ./travis_setup_env.sh

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=audio

script:
  - pytest