language: python
os: linux
dist: xenial

# Because Beryl is going to run on Python 3.6 or later
python:
  - "3.6"
  - "3.7"
  # - "3.8"
cache: pip

install:
  - pip install pipenv
  - pipenv install --dev

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=audio

script:
  - pipenv run pytest -v
